[2025-01-22T12:22:16.278+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 25_docker_hello_world.hello_world manual__2025-01-22T12:22:10.335910+00:00 [queued]>
[2025-01-22T12:22:16.290+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 25_docker_hello_world.hello_world manual__2025-01-22T12:22:10.335910+00:00 [queued]>
[2025-01-22T12:22:16.290+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-01-22T12:22:16.308+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): hello_world> on 2025-01-22 12:22:10.335910+00:00
[2025-01-22T12:22:16.317+0000] {standard_task_runner.py:60} INFO - Started process 1084 to run task
[2025-01-22T12:22:16.321+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '25_docker_hello_world', 'hello_world', 'manual__2025-01-22T12:22:10.335910+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/25_docker_hello_world.py', '--cfg-path', '/tmp/tmprv0um1vk']
[2025-01-22T12:22:16.324+0000] {standard_task_runner.py:88} INFO - Job 77: Subtask hello_world
[2025-01-22T12:22:16.341+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-01-22T12:22:16.387+0000] {task_command.py:423} INFO - Running <TaskInstance: 25_docker_hello_world.hello_world manual__2025-01-22T12:22:10.335910+00:00 [running]> on host b09fdc55415a
[2025-01-22T12:22:16.485+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='25_docker_hello_world' AIRFLOW_CTX_TASK_ID='hello_world' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T12:22:10.335910+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-22T12:22:10.335910+00:00'
[2025-01-22T12:22:16.505+0000] {docker.py:359} INFO - Starting docker container from image hello-world
[2025-01-22T12:22:16.510+0000] {docker.py:367} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-01-22T12:22:16.902+0000] {docker.py:429} INFO - Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/
[2025-01-22T12:22:17.115+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=25_docker_hello_world, task_id=hello_world, execution_date=20250122T122210, start_date=20250122T122216, end_date=20250122T122217
[2025-01-22T12:22:17.178+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-22T12:22:17.202+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
